### PR TITLE
Entropy?

### PR DESCRIPTION
**Pull request by worldspawn**
Not actually a PR. You mentioned u were interested in strength as entropy. #2

### CODE REVIEW

**Comment by subarroca** [comment]
What about giving the user the option to use entropy or ye olde formula?

**Comment by worldspawn** [comment]
Sure

**Comment by subarroca** [comment]
I just released a new version removing dependencies. Do you want to integrate optional entropy by yourself or should I do that?

**Comment by worldspawn** [comment]
I'm happy to do it

**Comment by subarroca** [comment]
merged but nor marked as so. See version 0.3.0

**Pull request closed without merging**
